import asyncio
import html
import logging
import os
import re
import sqlite3
from contextlib import closing
from datetime import datetime, timezone
from typing import Optional

from aiogram import Bot, Dispatcher, F, Router
from aiogram.client.default import DefaultBotProperties
from aiogram.enums import ParseMode
from aiogram.exceptions import TelegramBadRequest, TelegramForbiddenError
from aiogram.filters import Command, CommandStart, StateFilter
from aiogram.fsm.context import FSMContext
from aiogram.fsm.state import State, StatesGroup
from aiogram.types import (BotCommand, CallbackQuery, InlineKeyboardButton,
                           InlineKeyboardMarkup, Message)
from aiogram.utils.keyboard import InlineKeyboardBuilder
from dotenv import load_dotenv

load_dotenv()
TOKEN = os.getenv("BOT_TOKEN", "")
OWNER_ID = int(os.getenv("OWNER_ID", "8158007502"))
DATABASE = os.getenv("DATABASE_PATH", "paripulse.db")
REG_URL = os.getenv("REGISTRATION_URL", "https://example.com/register")
MANAGER_URL = os.getenv("MANAGER_URL", "https://t.me/manager_username")
ANIMATION_ID = os.getenv("WELCOME_ANIMATION_FILE_ID", "")
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()

logging.basicConfig(level=LOG_LEVEL, format="%(asctime)s | %(levelname)s | %(name)s | %(message)s")
log = logging.getLogger("paripulse")
router = Router()

LANGS = {"uz": "🇺🇿 O‘zbekcha", "ru": "🇷🇺 Русский", "en": "🇬🇧 English"}
T = {
 "choose_lang": "🌍 <b>Language Selection</b>\n\nTilni tanlang • Выберите язык • Choose a language",
 "welcome": {
  "uz": "👋 <b>Assalomu alaykum!</b>\n\n💎 PariPulse Affiliate Portal’iga xush kelibsiz.\n\nMen PariPulse bukmekerlik kompaniyasi Affiliate menejeri <b>Dilnazning virtual yordamchisiman</b>. 🤝\n\nBu yerda hamkorlikni boshlash, modellarni o‘rganish, ariza yuborish va menejer bilan bog‘lanish mumkin.\n\n✨ Kerakli bo‘limni tanlang:",
  "ru": "👋 <b>Здравствуйте!</b>\n\n💎 Добро пожаловать в PariPulse Affiliate Portal.\n\nЯ виртуальный помощник Affiliate-менеджера PariPulse <b>Дильназ</b>. 🤝\n\nЗдесь можно начать сотрудничество, изучить модели, подать заявку и связаться с менеджером.\n\n✨ Выберите раздел:",
  "en": "👋 <b>Welcome!</b>\n\n💎 Welcome to the PariPulse Affiliate Portal.\n\nI’m the virtual assistant of <b>Dilnaz</b>, Affiliate Manager at PariPulse. 🤝\n\nHere you can explore partnership models, apply and contact your manager.\n\n✨ Choose a section:"},
 "models": {
  "uz": "💎 <b>Hamkorlik modellari</b>\n\n📈 <b>RevShare — 35% gacha</b>\n+Siz olib kelgan o‘yinchilarning kompaniya sof daromadidan uzoq muddatli ulush. Foiz trafik sifati va hajmiga bog‘liq. Barqaror auditoriya uchun eng qulay model.\n\n🧾 <b>FIX</b>\n+Odatda 15 FTD test natijasidan keyin kelishiladi. Kuchli tajriba va tasdiqlangan statistika bo‘lsa, menejer individual shartlarni ko‘rib chiqadi.\n\n⚖️ <b>Hybrid</b>\n+Belgilangan to‘lov va RevShare kombinatsiyasi; shartlar individual kelishiladi.\n\n📬 <b>PostPay</b>\n+Natija tekshirilgach to‘lov; KPI va hisob-kitob davri menejer bilan belgilanadi.\n\n🚫 CPA modeli mavjud emas.",
  "ru": "💎 <b>Модели сотрудничества</b>\n\n📈 <b>RevShare — до 35%</b>\n+Долгосрочная доля от чистого дохода компании с привлечённых игроков. Процент зависит от объёма и качества трафика.\n\n🧾 <b>FIX</b>\n+Обычно обсуждается после теста на 15 FTD. При сильном опыте и подтверждённой статистике менеджер рассмотрит индивидуальные условия.\n\n⚖️ <b>Hybrid</b>\n+Комбинация фиксированной выплаты и RevShare; условия индивидуальны.\n\n📬 <b>PostPay</b>\n+Оплата после проверки результата; KPI и период согласуются с менеджером.\n\n🚫 CPA-модели нет.",
  "en": "💎 <b>Partnership models</b>\n\n📈 <b>RevShare — up to 35%</b>\n+A long-term share of net company revenue generated by your referred players. The rate depends on traffic volume and quality.\n\n🧾 <b>FIX</b>\n+Usually discussed after a 15 FTD test. Partners with strong experience and verified statistics may receive individual terms.\n\n⚖️ <b>Hybrid</b>\n+A combination of fixed payment and RevShare; terms are negotiated individually.\n\n📬 <b>PostPay</b>\n+Payment after results are verified; KPI and settlement period are agreed with the manager.\n\n🚫 CPA is not available."},
 "blocked": {"uz":"🔒 Avval menejer bilan faol suhbatni yoping.","ru":"🔒 Сначала закройте активный чат с менеджером.","en":"🔒 Please close your active manager chat first."},
}

class Apply(StatesGroup):
    email = State(); username = State(); channel = State(); rs = State(); geo = State(); promo = State()
class Ticket(StatesGroup):
    active = State()
class Admin(StatesGroup):
    broadcast = State(); direct_aff = State(); direct_text = State(); search = State(); add_admin = State()

def now(): return datetime.now(timezone.utc).isoformat(timespec="seconds")
def db():
    con = sqlite3.connect(DATABASE, timeout=30)
    con.row_factory = sqlite3.Row
    con.execute("PRAGMA foreign_keys=ON")
    con.execute("PRAGMA journal_mode=WAL")
    return con

def init_db():
    with closing(db()) as con:
        con.executescript("""
        CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, aff_id TEXT UNIQUE, username TEXT, full_name TEXT, lang TEXT DEFAULT 'uz', banned INTEGER DEFAULT 0, created_at TEXT NOT NULL);
        CREATE TABLE IF NOT EXISTS applications(id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, email TEXT, tg_user TEXT, channel TEXT, model TEXT, rs TEXT, geo TEXT, promo TEXT, status TEXT DEFAULT 'pending', created_at TEXT NOT NULL, reviewed_by INTEGER, reviewed_at TEXT, FOREIGN KEY(user_id) REFERENCES users(id));
        CREATE TABLE IF NOT EXISTS tickets(id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, status TEXT DEFAULT 'open', created_at TEXT NOT NULL, closed_at TEXT, FOREIGN KEY(user_id) REFERENCES users(id));
        CREATE TABLE IF NOT EXISTS ticket_messages(id INTEGER PRIMARY KEY AUTOINCREMENT, ticket_id INTEGER NOT NULL, sender_id INTEGER NOT NULL, sender_role TEXT NOT NULL, text TEXT, telegram_message_id INTEGER, created_at TEXT NOT NULL, FOREIGN KEY(ticket_id) REFERENCES tickets(id));
        CREATE TABLE IF NOT EXISTS admins(user_id INTEGER PRIMARY KEY, role TEXT NOT NULL DEFAULT 'admin', added_by INTEGER, created_at TEXT NOT NULL);
        CREATE INDEX IF NOT EXISTS ix_app_user ON applications(user_id); CREATE INDEX IF NOT EXISTS ix_ticket_user ON tickets(user_id,status);
        """)
        con.execute("INSERT OR IGNORE INTO admins(user_id,role,added_by,created_at) VALUES(?,?,?,?)", (OWNER_ID,"owner",OWNER_ID,now()))
        con.commit()

def ensure_user(m: Message):
    with closing(db()) as con:
        con.execute("INSERT OR IGNORE INTO users(id,username,full_name,created_at) VALUES(?,?,?,?)", (m.from_user.id,m.from_user.username,m.from_user.full_name,now()))
        con.execute("UPDATE users SET username=?,full_name=? WHERE id=?", (m.from_user.username,m.from_user.full_name,m.from_user.id)); con.commit()

def user_row(uid):
    with closing(db()) as con: return con.execute("SELECT * FROM users WHERE id=?",(uid,)).fetchone()
def lang(uid):
    r=user_row(uid); return (r["lang"] if r else "uz") or "uz"
def is_admin(uid):
    with closing(db()) as con: return con.execute("SELECT 1 FROM admins WHERE user_id=?",(uid,)).fetchone() is not None
def open_ticket(uid):
    with closing(db()) as con: return con.execute("SELECT * FROM tickets WHERE user_id=? AND status='open' ORDER BY id DESC LIMIT 1",(uid,)).fetchone()

def lang_kb():
    return InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text=v,callback_data=f"lang:{k}")] for k,v in LANGS.items()])
def main_kb(l):
    names={"uz":["💎 Hamkorlik modellari","📝 Ariza holati","💬 Menejer bilan chat","🌐 Til"],"ru":["💎 Модели сотрудничества","📝 Статус заявки","💬 Чат с менеджером","🌐 Язык"],"en":["💎 Partnership models","📝 Application status","💬 Manager chat","🌐 Language"]}[l]
    return InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text=names[0],callback_data="models")],[InlineKeyboardButton(text=names[1],callback_data="status")],[InlineKeyboardButton(text=names[2],callback_data="ticket:open")],[InlineKeyboardButton(text=names[3],callback_data="language")]])
def models_kb(l):
    apply={"uz":"🚀 RevShare bilan boshlash","ru":"🚀 Начать с RevShare","en":"🚀 Start with RevShare"}[l]
    talk={"uz":"💬 Boshqa modelni muhokama qilish","ru":"💬 Обсудить другую модель","en":"💬 Discuss another model"}[l]
    return InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text=apply,callback_data="rs:start")],[InlineKeyboardButton(text=talk,callback_data="ticket:open")],[InlineKeyboardButton(text="◀️ Menu",callback_data="menu")]])
def admin_kb():
    return InlineKeyboardMarkup(inline_keyboard=[
      [InlineKeyboardButton(text="📥 Yangi arizalar",callback_data="admin:apps"),InlineKeyboardButton(text="👥 Hamkorlar",callback_data="admin:partners")],
      [InlineKeyboardButton(text="🔎 Qidirish",callback_data="admin:search"),InlineKeyboardButton(text="📊 Statistika",callback_data="admin:stats")],
      [InlineKeyboardButton(text="📣 Broadcast",callback_data="admin:broadcast"),InlineKeyboardButton(text="✉️ AFF ID xabar",callback_data="admin:direct")],
      [InlineKeyboardButton(text="🛡 Adminlar",callback_data="admin:admins")]])

async def gate(q: CallbackQuery):
    r=user_row(q.from_user.id)
    if r and r["banned"]: await q.answer("🚫 Access denied",show_alert=True); return False
    if open_ticket(q.from_user.id) and not q.data.startswith("ticket:"):
        await q.answer(T["blocked"][lang(q.from_user.id)],show_alert=True); return False
    return True

@router.message(CommandStart())
async def start(m: Message, state: FSMContext):
    ensure_user(m); await state.clear()
    if user_row(m.from_user.id)["banned"]: return await m.answer("🚫 Access denied")
    await m.answer(T["choose_lang"],reply_markup=lang_kb())

@router.callback_query(F.data.startswith("lang:"))
async def set_lang(q: CallbackQuery, state: FSMContext):
    if not await gate(q): return
    l=q.data.split(":")[1]
    with closing(db()) as con: con.execute("UPDATE users SET lang=? WHERE id=?",(l,q.from_user.id)); con.commit()
    await state.clear(); await q.answer("✅")
    if ANIMATION_ID:
        try: await q.message.answer_animation(ANIMATION_ID,caption=T["welcome"][l],reply_markup=main_kb(l))
        except TelegramBadRequest: await q.message.answer(T["welcome"][l],reply_markup=main_kb(l))
    else: await q.message.edit_text(T["welcome"][l],reply_markup=main_kb(l))

@router.callback_query(F.data=="language")
async def language(q):
    if await gate(q): await q.message.edit_text(T["choose_lang"],reply_markup=lang_kb())
@router.callback_query(F.data=="menu")
async def menu(q):
    if await gate(q): await q.message.edit_text(T["welcome"][lang(q.from_user.id)],reply_markup=main_kb(lang(q.from_user.id)))
@router.callback_query(F.data=="models")
async def models(q):
    if await gate(q): await q.message.edit_text(T["models"][lang(q.from_user.id)],reply_markup=models_kb(lang(q.from_user.id)))

@router.callback_query(F.data=="rs:start")
async def rs_start(q):
    if not await gate(q): return
    l=lang(q.from_user.id); texts={"uz":"📈 <b>RevShare ro‘yxatdan o‘tish</b>\n\n1️⃣ Havolani oching\n2️⃣ Akkaunt yarating\n3️⃣ Quyidagi tugmani bosing", "ru":"📈 <b>Регистрация RevShare</b>\n\n1️⃣ Откройте ссылку\n2️⃣ Создайте аккаунт\n3️⃣ Нажмите кнопку ниже", "en":"📈 <b>RevShare registration</b>\n\n1️⃣ Open the link\n2️⃣ Create an account\n3️⃣ Press the button below"}
    done={"uz":"✅ Ro‘yxatdan o‘tdim","ru":"✅ Я зарегистрировался","en":"✅ I have registered"}[l]
    kb=InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text="🔗 Registration",url=REG_URL)],[InlineKeyboardButton(text=done,callback_data="apply:begin")]])
    await q.message.edit_text(texts[l],reply_markup=kb)

@router.callback_query(F.data=="apply:begin")
async def apply_begin(q, state: FSMContext):
    if not await gate(q): return
    await state.set_state(Apply.email); await state.update_data(model="RevShare")
    await q.message.answer("📧 <b>Email:</b>\n\nexample@gmail.com")
@router.message(Apply.email)
async def apply_email(m,state):
    v=(m.text or "").strip()
    if not re.fullmatch(r"[A-Za-z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+",v): return await m.answer("❌ Email formati noto‘g‘ri. Masalan: name@gmail.com")
    await state.update_data(email=v); await state.set_state(Apply.username); await m.answer("👤 <b>User:</b>\n\n@username")
@router.message(Apply.username)
async def apply_username(m,state):
    v=(m.text or "").strip()
    if not re.fullmatch(r"@[A-Za-z0-9_]{5,32}",v): return await m.answer("❌ Faqat @username formatida (5–32 belgi).")
    await state.update_data(tg_user=v); await state.set_state(Apply.channel); await m.answer("📣 <b>Kanal:</b>\n\nhttps://t.me/channel yoki @channel")
@router.message(Apply.channel)
async def apply_channel(m,state):
    v=(m.text or "").strip()
    if not (re.fullmatch(r"@[A-Za-z0-9_]{5,32}",v) or re.fullmatch(r"https?://(?:www\.)?t\.me/[A-Za-z0-9_]{5,32}/?",v,re.I)): return await m.answer("❌ Faqat Telegram kanal havolasi yoki @channel qabul qilinadi.")
    await state.update_data(channel=v); await state.set_state(Apply.rs)
    kb=InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text=f"📈 {x}%",callback_data=f"formrs:{x}%") for x in (25,30,35)]])
    await m.answer("📈 <b>RS:</b> Kerakli ulushni tanlang.",reply_markup=kb)
@router.callback_query(Apply.rs,F.data.startswith("formrs:"))
async def apply_rs(q,state):
    await state.update_data(rs=q.data.split(":")[1]); await state.set_state(Apply.geo)
    kb=InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text=x,callback_data=f"geo:{x}") for x in ("🇺🇿 UZ","🇰🇿 KZ")],[InlineKeyboardButton(text=x,callback_data=f"geo:{x}") for x in ("🇷🇺 RU","🌍 Mixed")]])
    await q.message.answer("🌍 <b>GEO:</b>",reply_markup=kb); await q.answer()
@router.callback_query(Apply.geo,F.data.startswith("geo:"))
async def apply_geo(q,state):
    await state.update_data(geo=q.data.split(":",1)[1]); await state.set_state(Apply.promo); await q.message.answer("🎁 <b>Promo:</b>\n\n3–24 ta lotin harfi yoki raqam."); await q.answer()
@router.message(Apply.promo)
async def apply_promo(m,state):
    v=(m.text or "").strip().upper()
    if not re.fullmatch(r"[A-Z0-9_-]{3,24}",v): return await m.answer("❌ Promo formati noto‘g‘ri.")
    d=await state.get_data(); uid=m.from_user.id
    with closing(db()) as con:
        existing=con.execute("SELECT id FROM applications WHERE user_id=? AND status='pending'",(uid,)).fetchone()
        if existing: await state.clear(); return await m.answer("⏳ Sizda ko‘rib chiqilayotgan ariza bor.",reply_markup=main_kb(lang(uid)))
        aff=con.execute("SELECT aff_id FROM users WHERE id=?",(uid,)).fetchone()[0]
        if not aff:
            seq=con.execute("SELECT COALESCE(MAX(CAST(SUBSTR(aff_id,5) AS INTEGER)),0)+1 FROM users WHERE aff_id IS NOT NULL").fetchone()[0]
            aff=f"AFF-{seq:06d}"; con.execute("UPDATE users SET aff_id=? WHERE id=?",(aff,uid))
        cur=con.execute("INSERT INTO applications(user_id,email,tg_user,channel,model,rs,geo,promo,created_at) VALUES(?,?,?,?,?,?,?,?,?)",(uid,d['email'],d['tg_user'],d['channel'],d['model'],d['rs'],d['geo'],v,now())); app_id=cur.lastrowid; con.commit()
    await state.clear(); await m.answer(f"✅ <b>Ariza yuborildi!</b>\n\n🆔 {aff}\n⏳ Menejer ko‘rib chiqadi.",reply_markup=main_kb(lang(uid)))
    await notify_admins(m.bot,app_id)

def app_card(a):
    return f"🆕 <b>HAMKOR ARIZASI #{a['id']}</b>\n━━━━━━━━━━━━━━\n🆔 {html.escape(a['aff_id'] or '—')}\n📧 Email: {html.escape(a['email'])}\n👤 User: {html.escape(a['tg_user'])}\n📣 Kanal: {html.escape(a['channel'])}\n💎 Model: {a['model']}\n📈 RS: {a['rs']}\n🌍 GEO: {a['geo']}\n🎁 Promo: {html.escape(a['promo'])}\n📌 Status: {a['status']}\n📅 {a['created_at']}"
async def notify_admins(bot,app_id):
    with closing(db()) as con:
        a=con.execute("SELECT a.*,u.aff_id FROM applications a JOIN users u ON u.id=a.user_id WHERE a.id=?",(app_id,)).fetchone(); admins=con.execute("SELECT user_id FROM admins").fetchall()
    kb=InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text="✅ Tasdiqlash",callback_data=f"review:approve:{app_id}"),InlineKeyboardButton(text="❌ Rad etish",callback_data=f"review:reject:{app_id}")],[InlineKeyboardButton(text="🚫 Ban",callback_data=f"ban:{a['user_id']}:1")]])
    for x in admins:
        try: await bot.send_message(x[0],app_card(a),reply_markup=kb)
        except (TelegramForbiddenError,TelegramBadRequest): pass

@router.callback_query(F.data=="status")
async def status(q):
    if not await gate(q): return
    with closing(db()) as con: a=con.execute("SELECT status,created_at FROM applications WHERE user_id=? ORDER BY id DESC LIMIT 1",(q.from_user.id,)).fetchone()
    await q.message.answer("📝 Ariza topilmadi." if not a else f"📝 <b>Ariza holati:</b> {a['status']}\n📅 {a['created_at']}")

@router.callback_query(F.data=="ticket:open")
async def ticket_open(q,state):
    r=user_row(q.from_user.id)
    if r and r["banned"]: return await q.answer("🚫",show_alert=True)
    t=open_ticket(q.from_user.id)
    if not t:
        with closing(db()) as con: tid=con.execute("INSERT INTO tickets(user_id,created_at) VALUES(?,?)",(q.from_user.id,now())).lastrowid; con.commit()
    else: tid=t["id"]
    await state.set_state(Ticket.active); await state.update_data(ticket_id=tid)
    kb=InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text="🔒 Suhbatni yopish",callback_data="ticket:close")]])
    await q.message.answer(f"💬 <b>Ticket #{tid} ochildi.</b>\n\nXabaringizni yuboring. Suhbat yopilmaguncha boshqa bo‘limlar bloklanadi.",reply_markup=kb); await q.answer()
@router.message(Ticket.active)
async def ticket_message(m,state):
    d=await state.get_data(); tid=d.get("ticket_id"); text=m.text or m.caption
    if not text: return await m.answer("❌ Hozircha faqat matn yuboring.")
    with closing(db()) as con:
        con.execute("INSERT INTO ticket_messages(ticket_id,sender_id,sender_role,text,telegram_message_id,created_at) VALUES(?,?,?,?,?,?)",(tid,m.from_user.id,"user",text,m.message_id,now())); admins=con.execute("SELECT user_id FROM admins").fetchall(); con.commit()
    kb=InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text="↩️ Javob",callback_data=f"ticketreply:{tid}:{m.from_user.id}")],[InlineKeyboardButton(text="🔒 Yopish",callback_data=f"ticketadminclose:{tid}:{m.from_user.id}")]])
    for a in admins:
        try: await m.bot.send_message(a[0],f"💬 <b>Ticket #{tid}</b>\n👤 {html.escape(m.from_user.full_name)} ({m.from_user.id})\n\n{html.escape(text)}",reply_markup=kb)
        except (TelegramForbiddenError,TelegramBadRequest): pass
    await m.answer("✅ Menejerga yetkazildi.")
@router.callback_query(F.data=="ticket:close")
async def ticket_close(q,state):
    t=open_ticket(q.from_user.id)
    if t:
        with closing(db()) as con: con.execute("UPDATE tickets SET status='closed',closed_at=? WHERE id=?",(now(),t['id'])); con.commit()
    await state.clear(); await q.message.answer("✅ Suhbat yopildi.",reply_markup=main_kb(lang(q.from_user.id))); await q.answer()

@router.message(Command("admin"))
async def admin(m,state):
    if not is_admin(m.from_user.id): return
    await state.clear(); await m.answer("🛡 <b>PariPulse CRM</b>",reply_markup=admin_kb())
@router.callback_query(F.data.startswith("review:"))
async def review(q):
    if not is_admin(q.from_user.id): return await q.answer("⛔",show_alert=True)
    _,action,sid=q.data.split(":"); status="approved" if action=="approve" else "rejected"
    with closing(db()) as con:
        a=con.execute("SELECT user_id,status FROM applications WHERE id=?",(sid,)).fetchone()
        if not a or a['status']!='pending': return await q.answer("Allaqachon ko‘rib chiqilgan",show_alert=True)
        con.execute("UPDATE applications SET status=?,reviewed_by=?,reviewed_at=? WHERE id=?",(status,q.from_user.id,now(),sid)); con.commit()
    try: await q.bot.send_message(a['user_id'],"✅ Arizangiz tasdiqlandi!" if status=='approved' else "❌ Arizangiz rad etildi. Tafsilot uchun menejer bilan bog‘laning.")
    except TelegramForbiddenError: pass
    await q.message.edit_reply_markup(reply_markup=None); await q.answer("✅")
@router.callback_query(F.data.startswith("ban:"))
async def ban(q):
    if not is_admin(q.from_user.id): return
    _,uid,val=q.data.split(":")
    with closing(db()) as con: con.execute("UPDATE users SET banned=? WHERE id=?",(int(val),int(uid))); con.commit()
    await q.answer("🚫 Banned" if val=="1" else "✅ Unbanned",show_alert=True)

@router.callback_query(F.data=="admin:stats")
async def stats(q):
    if not is_admin(q.from_user.id): return
    with closing(db()) as con:
        u=con.execute("SELECT COUNT(*) FROM users").fetchone()[0]; p=con.execute("SELECT COUNT(*) FROM applications WHERE status='pending'").fetchone()[0]; ok=con.execute("SELECT COUNT(*) FROM applications WHERE status='approved'").fetchone()[0]; t=con.execute("SELECT COUNT(*) FROM tickets WHERE status='open'").fetchone()[0]
    await q.message.answer(f"📊 <b>Statistika</b>\n\n👥 Users: {u}\n⏳ Pending: {p}\n✅ Approved: {ok}\n💬 Open tickets: {t}")
@router.callback_query(F.data=="admin:apps")
async def apps(q):
    if not is_admin(q.from_user.id): return
    with closing(db()) as con: rows=con.execute("SELECT a.*,u.aff_id FROM applications a JOIN users u ON u.id=a.user_id WHERE a.status='pending' ORDER BY a.id DESC LIMIT 10").fetchall()
    if not rows: return await q.message.answer("📭 Yangi ariza yo‘q.")
    for a in rows:
        kb=InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text="✅",callback_data=f"review:approve:{a['id']}"),InlineKeyboardButton(text="❌",callback_data=f"review:reject:{a['id']}")],[InlineKeyboardButton(text="🚫 Ban",callback_data=f"ban:{a['user_id']}:1")]])
        await q.message.answer(app_card(a),reply_markup=kb)
@router.callback_query(F.data=="admin:partners")
async def partners(q):
    if not is_admin(q.from_user.id): return
    with closing(db()) as con: rows=con.execute("SELECT u.*,a.status,a.email,a.geo FROM users u LEFT JOIN applications a ON a.id=(SELECT id FROM applications WHERE user_id=u.id ORDER BY id DESC LIMIT 1) WHERE u.aff_id IS NOT NULL ORDER BY u.id DESC LIMIT 30").fetchall()
    txt="👥 <b>Hamkorlar</b>\n\n"+"\n".join(f"🆔 {r['aff_id']} • {html.escape(r['full_name'] or '—')} • {r['status'] or '—'} • {r['geo'] or '—'}" for r in rows)
    await q.message.answer(txt if rows else "📭 Hamkorlar yo‘q.")
@router.callback_query(F.data=="admin:search")
async def search_begin(q,state):
    if not is_admin(q.from_user.id): return
    await state.set_state(Admin.search); await q.message.answer("🔎 AFF ID, Telegram ID yoki username kiriting:")
@router.message(Admin.search)
async def search_do(m,state):
    s=(m.text or "").strip(); key=s.lstrip("@");
    with closing(db()) as con: r=con.execute("SELECT * FROM users WHERE aff_id=? OR CAST(id AS TEXT)=? OR username=?",(s.upper(),s,key)).fetchone()
    await state.clear()
    if not r: return await m.answer("❌ Topilmadi.",reply_markup=admin_kb())
    kb=InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text="🚫 Ban" if not r['banned'] else "✅ Unban",callback_data=f"ban:{r['id']}:{0 if r['banned'] else 1}")]])
    await m.answer(f"👤 <b>{html.escape(r['full_name'] or '—')}</b>\n🆔 {r['aff_id'] or '—'}\n📱 {r['id']}\n@{r['username'] or '—'}\n🚫 Ban: {bool(r['banned'])}",reply_markup=kb)
@router.callback_query(F.data=="admin:broadcast")
async def broadcast_begin(q,state):
    if not is_admin(q.from_user.id): return
    await state.set_state(Admin.broadcast); await q.message.answer("📣 Barchaga yuboriladigan matnni kiriting. /cancel — bekor qilish.")
@router.message(Admin.broadcast)
async def broadcast_send(m,state):
    if m.text=="/cancel": await state.clear(); return await m.answer("Bekor qilindi.",reply_markup=admin_kb())
    with closing(db()) as con: users=con.execute("SELECT id FROM users WHERE banned=0").fetchall()
    ok=bad=0
    for u in users:
        try: await m.bot.send_message(u[0],m.text); ok+=1
        except (TelegramForbiddenError,TelegramBadRequest): bad+=1
        await asyncio.sleep(.04)
    await state.clear(); await m.answer(f"✅ Yuborildi: {ok}\n⚠️ Yetmadi: {bad}",reply_markup=admin_kb())
@router.callback_query(F.data=="admin:direct")
async def direct_begin(q,state):
    if not is_admin(q.from_user.id): return
    await state.set_state(Admin.direct_aff); await q.message.answer("🆔 AFF ID kiriting:")
@router.message(Admin.direct_aff)
async def direct_aff(m,state):
    with closing(db()) as con: r=con.execute("SELECT id FROM users WHERE aff_id=?",((m.text or '').strip().upper(),)).fetchone()
    if not r: return await m.answer("❌ AFF ID topilmadi. Qayta kiriting:")
    await state.update_data(target=r[0]); await state.set_state(Admin.direct_text); await m.answer("✉️ Xabar matnini kiriting:")
@router.message(Admin.direct_text)
async def direct_text(m,state):
    d=await state.get_data()
    try: await m.bot.send_message(d['target'],m.text); msg="✅ Yuborildi."
    except (TelegramForbiddenError,TelegramBadRequest): msg="❌ Xabar yetkazilmadi."
    await state.clear(); await m.answer(msg,reply_markup=admin_kb())
@router.callback_query(F.data=="admin:admins")
async def admins(q,state):
    if not is_admin(q.from_user.id): return
    with closing(db()) as con: rows=con.execute("SELECT * FROM admins").fetchall()
    text="🛡 <b>Adminlar</b>\n\n"+"\n".join(f"• {x['user_id']} — {x['role']}" for x in rows)
    if q.from_user.id==OWNER_ID:
        kb=InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text="➕ Admin qo‘shish",callback_data="admin:add")]])
        await q.message.answer(text,reply_markup=kb)
    else: await q.message.answer(text)
@router.callback_query(F.data=="admin:add")
async def add_admin_begin(q,state):
    if q.from_user.id!=OWNER_ID: return await q.answer("Owner only",show_alert=True)
    await state.set_state(Admin.add_admin); await q.message.answer("🛡 Yangi admin Telegram ID sini kiriting:")
@router.message(Admin.add_admin)
async def add_admin(m,state):
    if m.from_user.id!=OWNER_ID: return
    try: uid=int((m.text or '').strip())
    except ValueError: return await m.answer("❌ Faqat raqam kiriting.")
    with closing(db()) as con: con.execute("INSERT OR REPLACE INTO admins(user_id,role,added_by,created_at) VALUES(?,?,?,?)",(uid,"admin",OWNER_ID,now())); con.commit()
    await state.clear(); await m.answer("✅ Admin qo‘shildi.",reply_markup=admin_kb())

@router.callback_query(F.data.startswith("ticketreply:"))
async def ticket_reply_prompt(q,state):
    if not is_admin(q.from_user.id): return
    _,tid,uid=q.data.split(":"); await state.set_state(Admin.direct_text); await state.update_data(target=int(uid),ticket_id=int(tid)); await q.message.answer(f"↩️ Ticket #{tid} uchun javob yozing:"); await q.answer()
@router.callback_query(F.data.startswith("ticketadminclose:"))
async def ticket_admin_close(q):
    if not is_admin(q.from_user.id): return
    _,tid,uid=q.data.split(":")
    with closing(db()) as con: con.execute("UPDATE tickets SET status='closed',closed_at=? WHERE id=?",(now(),tid)); con.commit()
    try: await q.bot.send_message(int(uid),"🔒 Menejer suhbatni yopdi. /start orqali menyuga qayting.")
    except TelegramForbiddenError: pass
    await q.answer("Yopildi",show_alert=True)

@router.errors()
async def errors(event):
    log.exception("Unhandled update error",exc_info=event.exception); return True

async def main():
    if not TOKEN: raise RuntimeError("BOT_TOKEN is missing. Copy .env.example to .env and set the token.")
    init_db(); bot=Bot(TOKEN,default=DefaultBotProperties(parse_mode=ParseMode.HTML)); dp=Dispatcher(); dp.include_router(router)
    await bot.set_my_commands([BotCommand(command="start",description="🏠 Start / Menu"),BotCommand(command="admin",description="🛡 Admin panel")])
    log.info("PariPulse bot started"); await dp.start_polling(bot,allowed_updates=dp.resolve_used_update_types())

if __name__=="__main__": asyncio.run(main())
